### PR TITLE
ask git version from 1.7.10 to 1.8.1.6 since git log command needs

### PR DESCRIPTION
**Pull request by lunny**
see https://git-scm.com/docs/git-log/1.8.1.6 and this will fix go-gitea/gitea#1133

### CODE REVIEW

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
let L-G-T-M work

**Comment by strk** [comment]
What makes 1.8.1.5 not work, exactly ?

**Comment by lunny** [comment]
Yes, the minimal git version is 1.8.1.6

**Comment by strk** [comment]
My question was: why ? Do you have a reference to a CHANGELOG entry showing that 1.8.1.6 (and not just `1.8`) introduced a new feature we need here ?

**Comment by lunny** [comment]
@strk we have used `git log` in this repository but not clarify the git version. Then I find the minimal version requirement for `git log` is 1.8.1.6 in the URL I mentioned above. So I sent this PR. This is not a new feature, it's a missing requirement.

**Comment by strk** [comment]
tag v1.8.0 of git already has Documentation/git-log.txt, which was introduced by https://github.com/git/git/commit/215a7ad1ef790467a4cd3f0dcffbd6e5f04c38f7#diff-3fc88956ad5b506d1e9d081e702acbfc in 2005 - Even v0.99.7 had that commit...

**Comment by cez81** [comment]
@lunny Did you look at versions found at https://git-scm.com/docs/git-log? Even if 1.8.1.6 is first version listed it, it's not when command introduced. I have done that mistake myself...

**Comment by sapk** [comment]
https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.9.txt allready talk about `git log` command. I think that 1.8.1.6 is the first version with full documentation.

**Comment by sapk** [comment]
In light of the release date of 1.8.1.6 (more than 5 years) and packages version in common distribution. I give this PR my LGTM. It's not a bad thing to ask for "newer version" that limit possible incompatibility.

**Comment by strk** [comment]
I just find it weird to request a patch-level detailed version.
1.7+ would be enough for me, unless it's proved wrong.

**Comment by strk** [comment]
@sapk I just had problems with that meaningless strong dependency. Gogs run just fine on a Debian 6 but Hitea cannot, because it wants git 1.8 for no reason... I think t b is PR should be reverted

**Comment by tboerger** [comment]
Debian 6 is EOL since more than a year, so why should we care about that? It's not our problem if you are running such outdated systems...

**Comment by lunny** [comment]
Even Debian 6 could use backports to upgrade to git 1.9. High git version for security and performance. I don't think an too old version `git` support is needed.

**Comment by strk** [comment]
I hadn't found backports of git 1.9 for Debian 6, did you ?

We shouldn't make decisions for users, if a git version is too
old for our taste it isn't necessarely so for others.

Let's just not put arbitrary obstacles on the way to use Gitea, shall we ?

**Comment by strk** [comment]
Further discussion about this topic moved to #90

**Pull request merged**
