### PR TITLE
Add method to allow custom sorting of tree entry list

### PR DESCRIPTION
**Pull request by lafriks**
Needed to implement natural dir/file sorting in gitea

### CODE REVIEW

**Comment by bkcsoft** [comment]
Tests for this would be great :) Add it and you have my LG-TM 😉

**Comment by lafriks** [comment]
@bkcsoft added tests for tree entry sorting methods

**Comment by bkcsoft** [comment]
LGTM

**Comment by cez81** [comment]
LGTM

**Comment by cez81** [comment]
Make LG-TM work

**Pull request merged**
