### PR TITLE
Update copyright sentences

### PR DESCRIPTION
**Pull request by typeless**

### CODE REVIEW

**Comment by typeless** [comment]
Not sure if the is necessary if the files haven't been updated.

**Comment by strk** [comment]
Not only it isn't necessary, but it's also illegal. You cannot claim copyright of something you didn't write yourself.

Not that this whole thing necessarely matters because neither "The Gogs Authors" nor "The Gitea Authors" have any legal status ...

**Comment by typeless** [comment]
@strk Thanks for your info. That makes sense.

**Comment by bkcsoft** [comment]
@typeless @strk FWIW, if or when a file is updated by us, we could/should **add** `The Gitea Authors` on the first line, **keeping** `The Gogs Authors` just below it

**Pull request closed without merging**
