### PR TITLE
Introduce Blob.DataAsync

### PR DESCRIPTION
**Pull request by mrexodia**
This is a replacement for #47

I need this function for my refactor (related work: https://github.com/go-gitea/git/pull/93, https://github.com/go-gitea/gitea/pull/2990, https://github.com/go-gitea/gitea/issues/2669).

### CODE REVIEW

**Comment by mrexodia** [comment]
Ping @bkcsoft

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Comment by mrexodia** [comment]
Hm, so how can I update this in the main gitea repo? Or should I wait for #93 to be merged?

**Comment by lunny** [comment]
Execute `govender update code.gitea.io/git` on your gitea feature branch.

**Pull request merged**
