### PR TITLE
Don't trim trailing whitespaces for markdown

### PR DESCRIPTION
**Pull request by metalmatze**

### CODE REVIEW

**Comment by Bwko** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM but drone fails

**Comment by metalmatze** [comment]
> WARNING: unable to verify the Yaml signature.

I don't see how I should resolve drone failing.

**Comment by metalmatze** [comment]
Hm. Ok. I just recreated the drone signing. I don't understand how that broke. But LGTM now.

**Pull request merged**
