### PR TITLE
Fix variable name collision with import name

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
Fix variable name who collides with imported package name

### CODE REVIEW

**Comment by metalmatze** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM but travis failed

**Comment by 0xbaadf00d** [comment]
@tboerger yes but i not seems related to this PR

```
can't load package: package github.com/go-gitea/git: code in directory /home/travis/gopath/src/github.com/go-gitea/git expects import "code.gitea.io/git"
The command "eval go get -t -v ./..." failed. Retrying, 2 of 3.
```

**Comment by strk** [comment]
Travis failures are fixed by merging #6 , can you review that one please ?

**Pull request merged**
