### PR TITLE
Prefix commit ID in git log pretty to ease detection

### PR DESCRIPTION
**Pull request by lafriks**
Fixes https://github.com/go-gitea/gitea/issues/2064

### CODE REVIEW

**Comment by lafriks** [comment]
@ethantkoenig

**Comment by ethantkoenig** [comment]
@lafriks Unfortunately, this won't work. What if there is an entry that has only been affected by merge commits? If we ignore merge commits, we won't be able to find a commit for that entry.

I realize there are some problems with the current implementation of `GetCommitsInfo` (see #72), and I'm working on fixing them ASAP.

**Comment by lafriks** [comment]
@ethantkoenig How do you get merge commit with entries? I thought merge commit allways has child commit

**Comment by ethantkoenig** [comment]
@lafriks You can `git commit --amend` a merge commit, so a merge commit can contain arbitrary changes.

**Comment by lafriks** [comment]
I thought amend allows changing just commit message but OK, I will rework to ignore hashes with no entries

**Comment by ethantkoenig** [comment]
@lafriks In light of #72, all of this code will probably need to be rewritten (or at least heavily refactored), so I wouldn't bother (unless you really want to).

**Comment by ethantkoenig** [comment]
@lafriks I think we should revert to the old implementation of `GetCommitsInfo(..)` for the 1.2.0 release (see #73), so please close this issue.

**Comment by lafriks** [comment]
@ethantkoenig I have changed pretty format for `git log` command so that commit IDs would be prefixed and can be easily recognized

**Comment by ethantkoenig** [comment]
This does fix https://github.com/go-gitea/gitea/issues/2064, but it doesn't fix a lot of other known issues:

- if a file is changed in a merge commit (we don't ignore merge commits anymore, but it won't even show up in the first place using `git log --name-only`)
- #72

so I still think reverting (#73) is the best move right now.

**Pull request closed without merging**
