### PR TITLE
Tests for GetComimitsInfo

### PR DESCRIPTION
**Pull request by ethantkoenig**
In particular, adds test coverage for the bug fixed by #98.

### CODE REVIEW

**Comment by strk** [comment]
for a read-only test, like this one, why not using the code repository itself ? That's how I did it in repo_test.go. I know it may be fragile but seeing those objects in the repository sounds wrong to me. Maybe the cleanest would be for an initialization script to be run to create the repo ...

**Comment by lunny** [comment]
@strk's idea is what I want. But it's difficult to do in this repo. It could be in github.com/go-gitea/gitea's integration tests.

**Comment by ethantkoenig** [comment]
@strk: The disadvantage of using the repository itself is that you are limited in the number of scenarios you can test for (the commit history is essentially linear, and relying on branches other than master seems fragile since those branches may be deleted).

By adding a separate repository, we can create more scenarios for tests (e.g. two branches that have significantly diverged)

@lunny: It may be worthwhile to add an integration test in gitea, but I think it is important to also add a unit test in this repo. Otherwise, we could introduce a bug in this library, and will not realize until we update gitea's dependencies.

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
