### PR TITLE
Add lint check

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by strk** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM, but you also need to sign the drone config with the drone cli.

**Comment by lunny** [comment]
`drone sign <repo name>`, what's the repo name for gitea? @tboerger

**Comment by tboerger** [comment]
`drone sign go-gitea/gitea` :)

**Comment by lunny** [comment]
Why the new sign is so long?

**Pull request merged**
