### PR TITLE
Integrated drone and other standard files

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
Why giving up travis completely ?
From a quick look it seems that Travis is testing against multiple Go versions while Drone isn't (yet?).
Why not having both bots keep an eye on the code, until/unless they perform the same checks ?

**Comment by lunny** [comment]
Travis is too slow. Drone also can be configed Go versions.

**Comment by strk** [comment]
Let's have it configured before dropping travis

**Comment by tboerger** [comment]
Drone also got matrix builds and we define the build power and flexibility. Travis is slow and now we are really dogfooding as far as possible

**Comment by tboerger** [comment]
This pr is already complex enough, we can add the matrix later on as well

**Comment by metalmatze** [comment]
LGTM

**Comment by metalmatze** [comment]
Let's not forget to add the matrix later. Good job! :+1:

**Pull request merged**
